# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# Site settings
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Murky Blue
my_name: Blake Wolf
email: megalodon@murky.blue
description: >- # this means to ignore newlines until "baseurl:"
  Blake Wolf's digital domain.
domain: "murky.blue"
url: "https://murky.blue" # the base hostname & protocol for your site, e.g. http://example.com
threads_username: blakewolf.awooo
github_username:  cryptid-megalodon

# Build settings
theme: minima
plugins:
  - jekyll-feed

